# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  release:
    types:
      - created

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '3.1'
    - name: Setup nuget sources
      working-directory: ./src
      run: nuget sources add -Name Github -Source https://nuget.pkg.github.com/iteam-software/index.json -Username casjr13 -Password ${{ secrets.GPR_CASJR13_PAT }} -StorePasswordInClearText
    - name: Restore Packages
      working-directory: ./src
      run: dotnet restore
    - name: Build
      working-directory: ./src
      run: dotnet build EncompassRest -c Release --no-restore
    - name: Pack with dotnet
      working-directory: ./src
      run: dotnet pack EncompassRest -o ./packed -c Release --no-build /p:Version=${GITHUB_REF##*/}
    - name: Push with nuget
      working-directory: ./src
      run: dotnet nuget push ./packed/ -Source Github -SkipDuplicate
