# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  release:
    types:
      - created

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '3.1.x'      
    - name: Setup nuget sources
      run: nuget sources add -Name Github -Source https://nuget.pkg.github.com/iteam-software/index.json -Username casjr13 -Password ${{ secrets.FULL_ACCESS_TOKEN }} -StorePasswordInClearText
    - name: Restore Packages
      run: nuget restore
    - name: Pack with dotnet
      run: dotnet pack -o ./packed -c Release /p:Version=${GITHUB_REF##*/}
    - name: Push with nuget
      run: nuget push ./packed/ -Source Github -SkipDuplicate
