# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  release:
    types:
      - created

defaults:
  run:
    working-directory: ./src

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '3.1'
    #- name: Setup nuget sources
    #  working-directory: ./src
    #  run: nuget sources add -Name Github -Source https://nuget.pkg.github.com/iteam-software/index.json -Username casjr13 -Password ${{ secrets.GPR_CASJR13_PAT }} -StorePasswordInClearText
    - name: Restore Packages
      run: dotnet restore
    - name: Build
      run: dotnet build EncompassRest -c Release --no-restore
    - name: Pack with dotnet
      run: dotnet pack  EncompassRest -c Release -o ./packed --no-build /p:Version=${GITHUB_REF##*/}
    - name: Push with nuget
      run: dotnet nuget push ./packed/*.nupkg -k ${{ secrets.GPR_CASJR13_PAT }} -s https://nuget.pkg.github.com/iteam-software/index.json 
